version: '3.8'

services:
  wkas-app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: wkas-app
    restart: unless-stopped
    volumes:
      - ..:/var/www
    ports:
      - "8090:8090"
    networks:
      - mkas-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mkas-network:
    name: mkas-laravel_default
    external: true
