version: "3.8"

services:
  wkas-app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/wkas-laravel:latest
    container_name: wkas-app
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - mkas-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

networks:
  mkas-network:
    name: mkas-laravel_default
    external: true
